# Constants
# Error codes
SUCCESS = 0
ERROR = 1
CONNECTION_ACCEPT_ERROR = 2
CONNECTION_INITIATE_ERROR = 3
CONNECTION_CLOSE_ERROR = 4
LISTENING_SOCKET_CREATION_ERROR = 5
CONNECTION_SERVICE_ERROR = 6
KEYBOARD_INTERRUPT = 7
LISTENING_ERROR = 8
WAITING_ERROR = 9

# Variables
BYTES_TO_READ = 1
EOF_BYTE = b'\x00'
UPDATE_CHECK_REQUEST = b'10001'
UPDATE_DOWNLOAD_REQUEST = b'10002'
UPDATE_AVALIABLE = b'10003'
UPDATE_NOT_AVALIABLE = b'10004'